### ISSUE TITLE
Error: `The service was stopped`

### ISSUE THREAD

**Issue by nicksrandall** [codesandbox/nodebox-runtime#23]
I'm having a hard time debugging this issue. When I open in the project in codesandbox, everything works. 

When I run with sandpack, I get the following errors: 

```
worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105 The service was stopped
_0x20c137.<computed> @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
output @ dep-ca21228b.js:12543
error @ dep-ca21228b.js:12570
eval @ dep-ca21228b.js:42331
setTimeout (async)
refresh @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x461887 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x4dfa29 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
eval @ dep-ca21228b.js:42308
createDepsOptimizer @ dep-ca21228b.js:42306
await in createDepsOptimizer (async)
initDepsOptimizer @ dep-ca21228b.js:42206
eval @ dep-ca21228b.js:61433
await in eval (async)
initServer @ dep-ca21228b.js:61437
httpServer.listen @ dep-ca21228b.js:61445
eval @ dep-ca21228b.js:51520
httpServerStart @ dep-ca21228b.js:51502
startServer @ dep-ca21228b.js:61468
await in startServer (async)
listen @ dep-ca21228b.js:61247
eval @ cli.js:754
await in eval (async)
runMatchedCommand @ cli.js:660
parse @ cli.js:587
eval @ cli.js:901
_iterateThroughGenerator @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
await in _iterateThroughGenerator (async)
_finishLoading @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
load @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
await in load (async)
loadEsModule @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
dynamicImport @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x1d899e @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
start @ vite.js:46
eval @ vite.js:62
_iterateThroughGenerator @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
await in _iterateThroughGenerator (async)
_finishLoading @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
load @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
loadEsModule @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x16d150 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x12a9ec @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105 Uncaught Error: Process.exit called with exit code 2
    at globalThis.Go._0x481fa1 [as exit] (worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105:1030235)
    at runtime.wasmExit (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/wasm_exec.js:226:12)
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
    at wasm://wasm/0287ae4a
```

Followed by: 
```
worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105 2:28:19 PM [vite] Internal server error: The service is no longer running
  Plugin: vite:esbuild
  File: /nodebox/index.jsx
      at eval (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:787:29)
      at sendRequest (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:662:14)
      at start (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:785:9)
      at Object.transform2 [as transform] (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:842:5)
      at eval (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:1929:55)
      at new Promise (<anonymous>)
      at Object.transform (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:1929:14)
      at transform (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:1752:62)
      at transformWithEsbuild (nodebox:///nodebox/node_modules/.store/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13448:49)
      at TransformContext.transform (nodebox:///nodebox/node_modules/.store/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:13521:38)
      at Object.transform (nodebox:///nodebox/node_modules/.store/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41723:44)
      at async loadAndTransform (nodebox:///nodebox/node_modules/.store/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39517:29)
_0x20c137.<computed> @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
output @ dep-ca21228b.js:12543
error @ dep-ca21228b.js:12570
logError @ dep-ca21228b.js:41250
viteErrorMiddleware @ dep-ca21228b.js:41264
call @ dep-ca21228b.js:47362
next @ dep-ca21228b.js:47310
call @ dep-ca21228b.js:47375
next @ dep-ca21228b.js:47310
call @ dep-ca21228b.js:47375
next @ dep-ca21228b.js:47310
call @ dep-ca21228b.js:47375
next @ dep-ca21228b.js:47310
call @ dep-ca21228b.js:47375
next @ dep-ca21228b.js:47310
call @ dep-ca21228b.js:47375
next @ dep-ca21228b.js:47310
viteTransformMiddleware @ dep-ca21228b.js:60787
await in viteTransformMiddleware (async)
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
eval @ dep-ca21228b.js:39169
viteServePublicMiddleware @ dep-ca21228b.js:39219
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
next @ dep-ca21228b.js:47288
cors @ dep-ca21228b.js:47842
eval @ dep-ca21228b.js:47878
originCallback @ dep-ca21228b.js:47868
eval @ dep-ca21228b.js:47873
optionsCallback @ dep-ca21228b.js:47853
corsMiddleware @ dep-ca21228b.js:47858
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
handle @ dep-ca21228b.js:47313
app @ dep-ca21228b.js:47178
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x3a9228.<computed> @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x19a5c3 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
fire @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
handleMessage @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
xq138j5-5173.nodebox.codesandbox.io/:25          GET https://xq138j5-5173.nodebox.codesandbox.io/index.jsx net::ERR_ABORTED 500
worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105 2:28:19 PM [vite] error while updating dependencies:
Error: The service is no longer running
    at eval (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:1108:25)
    at sendRequest (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:662:14)
    at buildOrServeContinue (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:1106:5)
    at eval (nodebox:///nodebox/node_modules/.store/esbuild-wasm@0.15.12/node_modules/esbuild-wasm/lib/main.js:954:11)
_0x20c137.<computed> @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
output @ dep-ca21228b.js:12543
error @ dep-ca21228b.js:12570
runOptimizer @ dep-ca21228b.js:42494
await in runOptimizer (async)
rerun @ dep-ca21228b.js:42522
eval @ dep-ca21228b.js:42589
setTimeout (async)
refresh @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x461887 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x4dfa29 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
debouncedProcessing @ dep-ca21228b.js:42585
onCrawlEnd @ dep-ca21228b.js:42644
await in onCrawlEnd (async)
afterLoad @ dep-ca21228b.js:42703
Promise.catch (async)
runOptimizerWhenIdle @ dep-ca21228b.js:42712
afterLoad @ dep-ca21228b.js:42700
setTimeout (async)
refresh @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x461887 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x4dfa29 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
eval @ dep-ca21228b.js:42710
Promise.then (async)
runOptimizerWhenIdle @ dep-ca21228b.js:42709
afterLoad @ dep-ca21228b.js:42700
setTimeout (async)
refresh @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x461887 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x4dfa29 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
eval @ dep-ca21228b.js:42710
Promise.then (async)
runOptimizerWhenIdle @ dep-ca21228b.js:42709
afterLoad @ dep-ca21228b.js:42700
setTimeout (async)
refresh @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x461887 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x4dfa29 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
eval @ dep-ca21228b.js:42710
Promise.then (async)
runOptimizerWhenIdle @ dep-ca21228b.js:42709
delayDepsOptimizerUntil @ dep-ca21228b.js:42688
doTransform @ dep-ca21228b.js:39437
await in doTransform (async)
transformRequest @ dep-ca21228b.js:39399
viteTransformMiddleware @ dep-ca21228b.js:60741
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
viteServePublicMiddleware @ dep-ca21228b.js:39217
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
next @ dep-ca21228b.js:47288
cors @ dep-ca21228b.js:47842
eval @ dep-ca21228b.js:47878
originCallback @ dep-ca21228b.js:47868
eval @ dep-ca21228b.js:47873
optionsCallback @ dep-ca21228b.js:47853
corsMiddleware @ dep-ca21228b.js:47858
call @ dep-ca21228b.js:47366
next @ dep-ca21228b.js:47310
handle @ dep-ca21228b.js:47313
app @ dep-ca21228b.js:47178
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x3a9228.<computed> @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
_0x19a5c3 @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
fire @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
handleMessage @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
(anonymous) @ worker-kiri4aiwm06x1zrozbs6j1zxkkqx0ml.js:105
__csb_sw.4wa7ggdebk0h9uqz33slhe79sdhwmue.js:105 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': A ReadableStream could not be cloned because it was not transferred.
    at _0x393a80 (https://xq138j5-5173.nodebox.codesandbox.io/__csb_sw.4wa7ggdebk0h9uqz33slhe79sdhwmue.js:105:15805)
```

**Comment by DeMoorJasper** [comment]
Could you provide a minimal reproduction for this so we could debug this? Thanks in advance
